### ISSUE TITLE
Practica Front End  TLAXROOM

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-tlax-room#2]
[PRACTICA FRONT_END tlaxroom.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-tlax-room/files/6548783/PRACTICA.FRONT_END.tlaxroom.pdf)

**Comment by dulce-blm** [comment]
Calificación 30%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
